# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f332889f7ca9e8edf5558ae0519cff7dbb3e81142693bd28006ea7218c104981cb41aa26a6a0c132b45f754cd0636a6f6350b8d56e1a6243f8e0573723e3799d

test:
  secret_key_base: 074a55f4b8f8f265a22a72c70ad77db59cd98757115fa345d27aa9426bc628306831534a5d2f9a320d56d8a67f8db43f21e0cb7d5b5b061d13198ede738026c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
